spring:
  application:
     name: customer-purchase-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/597aa0a6-1546-4d8a-af67-47abe9558f00/v2.0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Navprabhat@10
    #driver-class-name: org.postgressql.Driver
  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true
  properties:
    hibernate:
      formate_sql: true

sql:
  init:
    mode: always

server:
  port: 8080

uiURL: http://localhost:5173

# Swagger Configuration
springdoc:
  api-docs:
     path: /api-docs
  swagger-ui:
     path: /swagger-ui.html



